### ISSUE TITLE
Allow channel name and description to expand

### ISSUE THREAD

**Issue by holmesal** [holmesal/hashtag#5]
Per mockups

**Comment by matthewkulp** [comment]
I like this.

I've been thinking that the descriptions should disappear over time. I think this because the description is really just a starting point to help others join and get onboarded to the discussion. 

But over time the channel takes on a characteristic of it's own, y'know. The description just becomes extra text in your face everytime you're at the channel screen.

**Comment by holmesal** [comment]
^ good point. Although in practice, I have actually found myself reading those descriptions when scanning the channel list, and it hasn't been a bad experience.

I'm on Day 1 of Living With Shortwave, so I'll keep paying attention and see if this starts feeling awkward.

**Comment by holmesal** [comment]
Closing this for now, the original issue was supposed to address the cells in the channel list moving from fixed to floating height.
